# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 203cb8c2bced4e3c1107fe940ff4d0f274ed2f438d05251cea3b09e408522247eccc54cb262cb2ed889be43297e2dead31970c3a9dbcb8c46025467fac6659db

test:
  secret_key_base: ff64a517f4afa0cbc11e29966a2934d17e1f2513cda9e176031d7c42354451a3fc4140f919a6693e1ef0812a9ad428cca5e1f691a2999b0d9f7fedb64452a8b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
